from PyQt6.QtGui import QPalette, QColor

def apply_theme(theme_name, app=None):
    palette = QPalette()
    
    if theme_name == "Dark":
        palette.setColor(QPalette.ColorRole.Window, QColor(53, 53, 53))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.Base, QColor(25, 25, 25))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(53, 53, 53))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.Text, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.Button, QColor(53, 53, 53))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(42, 130, 218))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(42, 130, 218))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Light":
        palette.setColor(QPalette.ColorRole.Window, QColor(240, 240, 240))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.Base, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(233, 231, 227))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(255, 255, 220))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.Text, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.Button, QColor(240, 240, 240))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(0, 0, 255))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(0, 120, 215))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))
    
    elif theme_name == "Futuristic":
        palette.setColor(QPalette.ColorRole.Window, QColor(10, 20, 40))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(0, 255, 255))
        palette.setColor(QPalette.ColorRole.Base, QColor(5, 10, 20))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(15, 30, 60))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(20, 40, 80))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(0, 255, 255))
        palette.setColor(QPalette.ColorRole.Text, QColor(200, 255, 255))
        palette.setColor(QPalette.ColorRole.Button, QColor(20, 40, 80))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(0, 255, 255))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(0, 200, 255))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(0, 150, 255))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Old Paper":
        palette.setColor(QPalette.ColorRole.Window, QColor(222, 211, 195))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(101, 67, 33))
        palette.setColor(QPalette.ColorRole.Base, QColor(245, 238, 223))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(235, 226, 208))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(255, 248, 220))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(101, 67, 33))
        palette.setColor(QPalette.ColorRole.Text, QColor(75, 50, 25))
        palette.setColor(QPalette.ColorRole.Button, QColor(200, 180, 150))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(101, 67, 33))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(150, 100, 50))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(180, 140, 100))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Fantasy":
        palette.setColor(QPalette.ColorRole.Window, QColor(139, 69, 19))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(255, 215, 0))
        palette.setColor(QPalette.ColorRole.Base, QColor(205, 133, 63))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(160, 82, 45))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(210, 180, 140))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.Text, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.Button, QColor(160, 82, 45))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(0, 100, 0))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(85, 107, 47))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))
    
    elif theme_name == "Relaxing":
        palette.setColor(QPalette.ColorRole.Window, QColor(173, 216, 230))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.Base, QColor(240, 248, 255))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(224, 255, 255))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(175, 238, 238))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.Text, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.Button, QColor(176, 224, 230))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(70, 130, 180))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(135, 206, 250))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    # New themes start here
    elif theme_name == "Midnight Blue":
        palette.setColor(QPalette.ColorRole.Window, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(220, 220, 220))
        palette.setColor(QPalette.ColorRole.Base, QColor(0, 0, 51))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(25, 25, 77))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(30, 30, 100))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(220, 220, 220))
        palette.setColor(QPalette.ColorRole.Text, QColor(220, 220, 220))
        palette.setColor(QPalette.ColorRole.Button, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(220, 220, 220))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(100, 149, 237))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(100, 149, 237))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Forest Green":
        palette.setColor(QPalette.ColorRole.Window, QColor(34, 139, 34))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(220, 255, 220))
        palette.setColor(QPalette.ColorRole.Base, QColor(0, 36, 0))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(25, 100, 25))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(50, 120, 50))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(220, 255, 220))
        palette.setColor(QPalette.ColorRole.Text, QColor(220, 255, 220))
        palette.setColor(QPalette.ColorRole.Button, QColor(34, 139, 34))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(220, 255, 220))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(144, 238, 144))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(144, 238, 144))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Sunset":
        palette.setColor(QPalette.ColorRole.Window, QColor(255, 140, 0))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(139, 0, 0))
        palette.setColor(QPalette.ColorRole.Base, QColor(255, 218, 185))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(240, 128, 128))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(255, 160, 122))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(139, 0, 0))
        palette.setColor(QPalette.ColorRole.Text, QColor(139, 0, 0))
        palette.setColor(QPalette.ColorRole.Button, QColor(255, 165, 0))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(139, 0, 0))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(255, 140, 0))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(255, 140, 0))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))
    
    elif theme_name == "Ocean":
        palette.setColor(QPalette.ColorRole.Window, QColor(102, 205, 170))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(0, 139, 139))
        palette.setColor(QPalette.ColorRole.Base, QColor(224, 255, 255))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(175, 238, 238))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(176, 224, 230))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(0, 139, 139))
        palette.setColor(QPalette.ColorRole.Text, QColor(0, 139, 139))
        palette.setColor(QPalette.ColorRole.Button, QColor(102, 205, 170))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(0, 139, 139))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(70, 130, 180))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(70, 130, 180))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))
    
    elif theme_name == "Desert":
        palette.setColor(QPalette.ColorRole.Window, QColor(244, 164, 96))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(139, 69, 19))
        palette.setColor(QPalette.ColorRole.Base, QColor(245, 222, 179))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(210, 180, 140))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(222, 184, 135))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(139, 69, 19))
        palette.setColor(QPalette.ColorRole.Text, QColor(139, 69, 19))
        palette.setColor(QPalette.ColorRole.Button, QColor(244, 164, 96))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(139, 69, 19))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(205, 133, 63))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(205, 133, 63))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))
    
    elif theme_name == "High Contrast":
        palette.setColor(QPalette.ColorRole.Window, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.Base, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(20, 20, 20))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(255, 255, 0))
        palette.setColor(QPalette.ColorRole.Text, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.Button, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(0, 255, 255))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(255, 255, 0))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Purple Haze":
        palette.setColor(QPalette.ColorRole.Window, QColor(75, 0, 130))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(230, 230, 250))
        palette.setColor(QPalette.ColorRole.Base, QColor(35, 0, 60))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(93, 63, 211))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(147, 112, 219))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(230, 230, 250))
        palette.setColor(QPalette.ColorRole.Text, QColor(230, 230, 250))
        palette.setColor(QPalette.ColorRole.Button, QColor(75, 0, 130))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(230, 230, 250))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 105, 180))
        palette.setColor(QPalette.ColorRole.Link, QColor(238, 130, 238))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(238, 130, 238))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Crimson":
        palette.setColor(QPalette.ColorRole.Window, QColor(139, 0, 0))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(255, 228, 225))
        palette.setColor(QPalette.ColorRole.Base, QColor(60, 0, 0))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(100, 0, 0))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(205, 92, 92))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(255, 228, 225))
        palette.setColor(QPalette.ColorRole.Text, QColor(255, 228, 225))
        palette.setColor(QPalette.ColorRole.Button, QColor(139, 0, 0))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(255, 228, 225))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 255, 224))
        palette.setColor(QPalette.ColorRole.Link, QColor(240, 128, 128))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(240, 128, 128))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Matrix":
        palette.setColor(QPalette.ColorRole.Window, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(0, 255, 0))
        palette.setColor(QPalette.ColorRole.Base, QColor(0, 20, 0))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(0, 40, 0))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(0, 50, 0))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(0, 255, 0))
        palette.setColor(QPalette.ColorRole.Text, QColor(0, 255, 0))
        palette.setColor(QPalette.ColorRole.Button, QColor(0, 0, 0))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(0, 255, 0))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(0, 255, 127))
        palette.setColor(QPalette.ColorRole.Link, QColor(0, 255, 0))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(0, 255, 0))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(0, 0, 0))
    
    elif theme_name == "Winter":
        palette.setColor(QPalette.ColorRole.Window, QColor(225, 240, 255))
        palette.setColor(QPalette.ColorRole.WindowText, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.Base, QColor(255, 255, 255))
        palette.setColor(QPalette.ColorRole.AlternateBase, QColor(240, 240, 240))
        palette.setColor(QPalette.ColorRole.ToolTipBase, QColor(224, 255, 255))
        palette.setColor(QPalette.ColorRole.ToolTipText, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.Text, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.Button, QColor(176, 196, 222))
        palette.setColor(QPalette.ColorRole.ButtonText, QColor(25, 25, 112))
        palette.setColor(QPalette.ColorRole.BrightText, QColor(255, 0, 0))
        palette.setColor(QPalette.ColorRole.Link, QColor(70, 130, 180))
        palette.setColor(QPalette.ColorRole.Highlight, QColor(70, 130, 180))
        palette.setColor(QPalette.ColorRole.HighlightedText, QColor(255, 255, 255))
    
    return palette
